/*
 *  Copyright (C) 2023 Cojen.org
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.cojen.tupl.model;

import org.cojen.tupl.Table;

import org.cojen.tupl.rows.RowUtils;

/**
 * Represents a factory for making tables or query result sets.
 *
 * @author Brian S. O'Neill
 * @see RelationNode
 */
// FIXME: see org.cojen.tupl.jdbc.DbQuery
public interface QueryFactory<R> {
    Class<R> rowType();

    /**
     * Returns the minimum amount of arguments which must be passed to the {@link #table}
     * method.
     */
    int argumentCount();

    /**
     * Returns a fully functional table.
     *
     * @throws IllegalArgumentException if not enough arguments are given
     */
    Table<R> table(Object... args);

    default Table<R> table() {
        return table(RowUtils.NO_ARGS);
    }

    // FIXME
    //DbQuery newDbQuery(DbConnection con)

    /*
      FIXME: Provide access to the projected column names, which can differ from the table
      column names. This should be a LinkedHashMap, generated by RelationType.
      * @return unmodifiable map of row field names to labels
      Map<String, String> columnLabels();
    */

    /**
     * Returns a QueryFactory which just wraps a Table.
     */
    public static <R> QueryFactory<R> make(Table<R> table) {
        return new QueryFactory<>() {
            @Override
            public Class<R> rowType() {
                return table.rowType();
            }

            @Override
            public int argumentCount() {
                return 0;
            }

            @Override
            public Table<R> table(Object... args) {
                return table;
            }
        };
    }

    public static abstract class Wrapped implements QueryFactory {
        protected final QueryFactory mSource;
        protected final int mArgCount;

        protected Wrapped(QueryFactory source, int argCount) {
            mSource = source;
            mArgCount = argCount;
        }

        @Override
        public final Class rowType() {
            return mSource.rowType();
        }

        @Override
        public final int argumentCount() {
            return mArgCount;
        }

        protected final int checkArgumentCount(Object... args) {
            int argCount = mArgCount;
            if (args.length < argCount) {
                throw new IllegalArgumentException("Not enough query arguments provided");
            }
            return argCount;
        }
    }
}
