/*
 *  Copyright 2016 Cojen.org
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.cojen.tupl;

import java.io.InterruptedIOException;
import java.io.IOException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Set;

import java.util.concurrent.Executor;

import static org.cojen.tupl.DirectPageOps.*;

/**
 * Sorter which performs a multi-level parallel merge sort.
 *
 * @author Generated by PageAccessTransformer from ParallelSorter.java
 */
/*P*/
class _ParallelSorter implements Sorter {
    private static final int SORT_NODES = 64; // absolute max allowed is 32768
    private static final int L0_MAX_SIZE = 256; // max number of trees at first level
    private static final int L1_MAX_SIZE = 1024; // max number of trees at higher levels

    private static final int MERGE_THREAD_COUNT = Runtime.getRuntime().availableProcessors();

    private final _LocalDatabase mDatabase;

    // Top of active sort node stack.
    private _Node mSortNodeTop;
    private int mSortNodeCount;

    // Top of recycled sort node stack.
    private _Node mNodePoolTop;

    private List<List<_Tree>> mSortTreeLevels;

    // FIXME: Extend Latch and lazy init mActiveMergers (?)
    private final Set<_TreeMerger> mActiveMergers;
    private int mActiveNodeMergers;

    private final Executor mExecutor;

    private boolean mFinishing;

    _ParallelSorter(_LocalDatabase db, Executor executor) {
        mDatabase = db;
        mActiveMergers = new HashSet<>();
        mExecutor = executor;
    }

    @Override
    public synchronized void add(byte[] key, byte[] value) throws IOException {
        _Node node = mSortNodeTop;

        CommitLock lock = mDatabase.commitLock();
        lock.lock();
        try {
            if (node == null) {
                node = allocSortNode();
                mSortNodeTop = node;
                mSortNodeCount = 1;
            } else {
                latchDirty(node);
            }

            try {
                node = _Node.appendToSortLeaf(node, mDatabase, key, value, this::nextSortNode);
            } finally {
                node.releaseExclusive();
            }
        } finally {
            lock.unlock();
        }
    }

    @Override
    public Index finish() throws IOException {
        try {
            return doFinish();
        } finally {
            // FIXME: Only reset if exception; doFinish does the work.
            reset();
        }
    }

    @Override
    public synchronized void reset() throws IOException {
        // FIXME: implement reset
        /* drain the pool...
        node.makeEvictable();
        mDatabase.deleteNode(node);
        */
    }

    // Caller must be synchronized.
    private void checkFinishing() {
        if (mFinishing) {
            throw new IllegalStateException("finish in progress");
        }
    }

    private _Tree doFinish() throws IOException {
        synchronized (this) {
            checkFinishing();

            mFinishing = true;

            _Node topNode = mSortNodeTop;
            int count = mSortNodeCount;
            mSortNodeTop = null;
            mSortNodeCount = 0;

            while (mActiveNodeMergers > 0) {
                try {
                    wait();
                } catch (InterruptedException e) {
                    throw new InterruptedIOException();
                }
            }

            if (topNode == null) {
                if (mSortTreeLevels == null || mSortTreeLevels.isEmpty()) {
                    return mDatabase.newTemporaryIndex();
                }
            } else {
                _Tree tree;
                if (count == 1) {
                    latchDirty(topNode);
                    topNode.sortLeaf();
                    topNode.releaseExclusive();
                    // FIXME: node must not be discarded by undo log
                    // FIXME: commit lock!
                    tree = mDatabase.newTemporaryTree(topNode);
                } else {
                    tree = doMergeNodes(topNode, count);
                }
                if (mSortTreeLevels == null || mSortTreeLevels.isEmpty()) {
                    return tree;
                }
                addToLevel(tree, 0, L0_MAX_SIZE);
            }
        }

        waitForInactivity(true);

        List<_Tree> allTrees;
        synchronized (this) {
            if (mSortTreeLevels.size() == 1) {
                allTrees = mSortTreeLevels.get(0);
            } else {
                int allTreeCount = 0;
                for (int i=mSortTreeLevels.size(); --i>=0; ) {
                    allTreeCount += mSortTreeLevels.get(i).size();
                }

                allTrees = new ArrayList<>(allTreeCount);

                // Iterate in reverse order to favor duplicates at lower levels, which were
                // added more recently.
                for (int i=mSortTreeLevels.size(); --i>=0; ) {
                    List<_Tree> trees = mSortTreeLevels.get(i);
                    allTrees.addAll(trees);
                    trees.clear();
                }
            }

            if (allTrees.size() <= 1) {
                _Tree tree;
                if (allTrees.isEmpty()) {
                    tree = mDatabase.newTemporaryIndex();
                } else {
                    tree = allTrees.get(0);
                }
                mSortTreeLevels.clear();
                return tree;
            }
        }

        mergeTrees(allTrees, 0);

        waitForInactivity(false);

        synchronized (this) {
            _Tree tree = mSortTreeLevels.get(0).get(0);
            mSortTreeLevels.clear();
            return tree;
        }
    }

    private void waitForInactivity(boolean stop) throws InterruptedIOException {
        try {
            synchronized (mActiveMergers) {
                if (stop) {
                    for (_TreeMerger m : mActiveMergers) {
                        m.stop();
                    }
                }

                while (!mActiveMergers.isEmpty()) {
                    mActiveMergers.wait();
                }
            }
        } catch (InterruptedException e) {
            throw new InterruptedIOException();
        }
    }

    private void finished(_TreeMerger merger) {
        synchronized (mActiveMergers) {
            mActiveMergers.remove(merger);
            if (mActiveMergers.isEmpty()) {
                mActiveMergers.notifyAll();
            }
        }

        // FIXME: capture this
        System.out.println("ex: " + merger.exceptionCheck());
    }

    // Caller must be synchronized and hold commit lock.
    private _Node nextSortNode(_Node current) throws IOException {
        current.releaseExclusive();
        if (mSortNodeCount >= SORT_NODES) {
            mergeNodes();
        }
        _Node next = allocSortNode();
        next.mLessUsed = mSortNodeTop;
        mSortNodeTop = next;
        mSortNodeCount++;
        return next;
    }

    // Caller must be synchronized.
    private void mergeNodes() throws IOException {
        // Merge the nodes into a new temporary index.

        _Node topNode = mSortNodeTop;
        int count = mSortNodeCount;
        mSortNodeTop = null;
        mSortNodeCount = 0;

        mActiveNodeMergers++;
        try {
            mExecutor.execute(() -> {
                _Tree tree;
                try {
                    tree = doMergeNodes(topNode, count);
                } catch (Throwable e) {
                    synchronized (this) {
                        mActiveNodeMergers--;
                        notifyAll();
                    }
                    // FIXME: stash it for later
                    throw Utils.rethrow(e);
                }

                synchronized (this) {
                    mActiveNodeMergers--;
                    try {
                        addToLevel(tree, 0, L0_MAX_SIZE);
                    } catch (Throwable e) {
                        // FIXME: stash it for later
                        throw Utils.rethrow(e);
                    } finally {
                        notifyAll();
                    }
                }
            });
        } catch (Throwable e) {
            mActiveNodeMergers--;
            notifyAll();
            throw e;
        }
    }

    /**
     * @return new temporary index
     */
    private _Tree doMergeNodes(_Node topNode, int count) throws IOException {
        PriorityQueue<_Node> pq = new PriorityQueue<>(count, _ParallelSorter::compareSortNode);

        do {
            latchDirty(topNode);
            topNode.sortLeaf();

            // Use the garbage field for encoding the node order. Bit 0 is used for detecting
            // duplicates.
            topNode.garbage((--count) << 1);
            pq.add(topNode);

            _Node less = topNode.mLessUsed;
            topNode.mLessUsed = null;
            topNode = less;
        } while (count > 0);

        _Tree dest = mDatabase.newTemporaryIndex();

        _TreeCursor appender = dest.newCursor(Transaction.BOGUS);
        try {
            appender.firstAny();
            for (_Node node; (node = pq.poll()) != null; ) {
                int order = node.garbage();
                if ((order & 1) == 0) {
                    appender.appendTransfer(node);
                } else {
                    // _Node has a duplicate entry which must be deleted.
                    node.deleteFirstSortLeafEntry();
                    node.garbage(order & ~1);
                }

                if (node.hasKeys()) {
                    pq.add(node);
                } else {
                    // Recycle the node.
                    node.releaseExclusive();
                    synchronized (this) {
                        node.mLessUsed = mNodePoolTop;
                        mNodePoolTop = node;
                    }
                }
            }
        } finally {
            appender.reset();
        }

        return dest;
    }

    // Caller must be synchronized and hold commit lock.
    private _Node allocSortNode() throws IOException {
        checkFinishing();

        _Node node = mNodePoolTop;
        if (node == null) {
            // FIXME: Track node using a special op in an _UndoLog instance.
            node = mDatabase.allocDirtyNode(_NodeUsageList.MODE_UNEVICTABLE);
        } else {
            mNodePoolTop = node.mLessUsed;
            node.mLessUsed = null;
            latchDirty(node);
        }

        node.asSortLeaf();
        return node;
    }

    private static int compareSortNode(_Node left, _Node right) {
        try {
            int compare = _Node.compareKeys
                (left, p_ushortGetLE(left.mPage, left.searchVecStart()),
                 right, p_ushortGetLE(right.mPage, right.searchVecStart()));

            if (compare == 0) {
                // Use node order (encoded in garbage field) for eliminating duplicates.
                // Signal that the first entry from the node with the lower key must be
                // deleted. Use bit 0 to signal this.

                int leftOrder = left.garbage();
                int rightOrder = right.garbage();

                if (leftOrder < rightOrder) {
                    left.garbage(leftOrder | 1);
                    compare = -1;
                } else {
                    right.garbage(rightOrder | 1);
                    compare = 1;
                }
            }

            return compare;
        } catch (Throwable e) {
            throw Utils.rethrow(e);
        }
    }

    private void latchDirty(_Node node) throws IOException {
        node.acquireExclusive();
        try {
            // FIXME: When id changes... oops! Needs to be tracked again in undo log.
            // FIXME: Not all callers hold commit lock!
            // FIXME: If shouldMarkDirty, then don't. Allocate a new node instead. Rollback the
            // transaction which is tracking the nodes, deleting them. The prepareToDelete
            // method ensures that changes destined for the checkpoint are flushed out.
            mDatabase.markUnmappedDirty(node);
        } catch (Throwable e) {
            node.releaseExclusive();
            throw e;
        }
    }

    // Caller must be synchronized.
    private void addToLevel(_Tree tree, int level, int maxLevelSize) throws IOException {
        if (mSortTreeLevels == null) {
            mSortTreeLevels = new ArrayList<>();
        } else if (level < mSortTreeLevels.size()) {
            List<_Tree> trees = mSortTreeLevels.get(level);
            trees.add(tree);
            if (trees.size() >= maxLevelSize && !mFinishing) {
                mergeTrees(trees, level + 1);
            }
            return;
        }
        List<_Tree> trees = new ArrayList<>();
        trees.add(tree);
        mSortTreeLevels.add(trees);
    }

    private void mergeTrees(List<_Tree> trees, int targetLevel) throws IOException {
        _Tree[] toMerge = trees.toArray(new _Tree[trees.size()]);
        trees.clear();

        _TreeMerger tm = new _TreeMerger
            (mDatabase, MERGE_THREAD_COUNT, toMerge, (merger, target) -> {
                if (target == null) {
                    finished(merger);
                } else {
                    try {
                        synchronized (this) {
                            addToLevel(target, targetLevel, L1_MAX_SIZE);
                        }
                    } catch (Throwable e) {
                        throw Utils.rethrow(e);
                    }
                }
            });

        synchronized (mActiveMergers) {
            mActiveMergers.add(tm);
        }

        tm.start(mExecutor);
    }
}
