/*
 *  Copyright 2015 Cojen.org
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.cojen.tupl;

import java.io.IOException;

/**
 * Undo log and a set of exclusive locks from a transaction ready to be committed.
 *
 * @author Generated by PageAccessTransformer from PendingTxn.java
 */
/*P*/
final class _PendingTxn extends _LockOwner {
    private final _Lock mFirst;
    private _Lock[] mRest;
    private int mRestSize;

    _TransactionContext mTxnContext;
    long mTxnId;
    long mCommitPos;
    _UndoLog mUndoLog;
    boolean mHasFragmentedTrash;
    private Object mAttachment;

    _PendingTxn mPrev;

    _PendingTxn(_Lock first) {
        mFirst = first;
    }

    @Override
    public final _LocalDatabase getDatabase() {
        return mUndoLog.getDatabase();
    }

    @Override
    public void attach(Object obj) {
        mAttachment = obj;
    }

    @Override
    public Object attachment() {
        return mAttachment;
    }

    /**
     * Add an exclusive lock into the set, retaining FIFO (queue) order.
     */
    void add(_Lock lock) {
        _Lock first = mFirst;
        if (first == null) {
            throw new IllegalStateException("cannot add lock");
        }
        _Lock[] rest = mRest;
        if (rest == null) {
            rest = new _Lock[8];
            mRest = rest;
            mRestSize = 1;
            rest[0] = lock;
        } else {
            int size = mRestSize;
            if (size >= rest.length) {
                _Lock[] newRest = new _Lock[rest.length << 1];
                System.arraycopy(rest, 0, newRest, 0, rest.length);
                mRest = rest = newRest;
            }
            rest[size] = lock;
            mRestSize = size + 1;
        }
    }

    /**
     * Releases all the locks and then discards the undo log. This object must be discarded
     * afterwards.
     */
    void commit(_LocalDatabase db) throws IOException {
        // See Transaction.commit for more info.

        unlockAll(db);

        _UndoLog undo = mUndoLog;
        if (undo != null) {
            undo.truncate(true);
            mTxnContext.unregister(undo);
        }

        if (mHasFragmentedTrash) {
            db.fragmentedTrash().emptyTrash(mTxnId);
        }
    }

    /**
     * Applies the undo log, releases all the locks, and then discards the undo log. This
     * object must be discarded afterwards.
     */
    void rollback(_LocalDatabase db) throws IOException {
        // See Transaction.exit for more info.

        _UndoLog undo = mUndoLog;
        if (undo != null) {
            undo.rollback();
        }

        unlockAll(db);

        if (undo != null) {
            mTxnContext.unregister(undo);
        }
    }

    private void unlockAll(_LocalDatabase db) {
        _Lock first = mFirst;
        if (first != null) {
            _LockManager manager = db.mLockManager;
            manager.unlock(this, first);
            _Lock[] rest = mRest;
            if (rest != null) {
                for (_Lock lock : rest) {
                    if (lock == null) {
                        return;
                    }
                    manager.unlock(this, lock);
                }
            }
        }
    }
}
