/*
 *  Copyright (C) 2011-2017 Cojen.org
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.cojen.tupl;

import java.io.IOException;

/**
 * _TreeCursor which prohibits redo durabilty.
 *
 * @author Generated by PageAccessTransformer from TempTreeCursor.java
 */
/*P*/
final class _TempTreeCursor extends _TreeCursor {
    _TempTreeCursor(_TempTree tree, Transaction txn) {
        super(tree, txn);
    }

    _TempTreeCursor(_TempTree tree) {
        super(tree);
    }

    @Override
    public final void store(byte[] value) throws IOException {
        byte[] key = mKey;
        ViewUtils.positionCheck(key);

        try {
            final _LocalTransaction txn = mTxn;
            if (txn == null) {
                store(_LocalTransaction.BOGUS, leafExclusive(), value);
            } else {
                if (txn.lockMode() != LockMode.UNSAFE) {
                    txn.lockExclusive(mTree.mId, key, keyHash());
                }
                _CursorFrame leaf = leafExclusive();
                final DurabilityMode dmode = txn.durabilityMode();
                if (dmode == DurabilityMode.NO_REDO) {
                    store(txn, leaf, value);
                } else {
                    txn.durabilityMode(DurabilityMode.NO_REDO);
                    try {
                        store(txn, leaf, value);
                    } finally {
                        txn.durabilityMode(dmode);
                    }
                }
            }
        } catch (Throwable e) {
            throw handleException(e, false);
        }
    }

    @Override
    public final void commit(byte[] value) throws IOException {
        byte[] key = mKey;
        ViewUtils.positionCheck(key);

        try {
            final _LocalTransaction txn = mTxn;
            if (txn == null) {
                store(_LocalTransaction.BOGUS, leafExclusive(), value);
            } else {
                if (txn.lockMode() != LockMode.UNSAFE) {
                    txn.lockExclusive(mTree.mId, key, keyHash());
                }
                _CursorFrame leaf = leafExclusive();
                final DurabilityMode dmode = txn.durabilityMode();
                if (dmode == DurabilityMode.NO_REDO) {
                    store(txn, leaf, value);
                } else {
                    txn.durabilityMode(DurabilityMode.NO_REDO);
                    try {
                        store(txn, leaf, value);
                    } finally {
                        txn.durabilityMode(dmode);
                    }
                }
                txn.commit();
            }
        } catch (Throwable e) {
            throw handleException(e, false);
        }
    }
}
