/*
 *  Copyright (C) 2011-2017 Cojen.org
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.cojen.tupl;

import java.lang.ref.ReferenceQueue;
import java.lang.ref.WeakReference;

/**
 * Allows open Trees to be unloaded when no longer in use.
 *
 * @author Generated by PageAccessTransformer from TreeRef.java
 */
/*P*/
final class _TreeRef extends WeakReference<_Tree> {
    final long mId;
    final byte[] mName;
    final _Node mRoot;

    _TreeRef(_Tree tree, ReferenceQueue<? super _Tree> queue) {
        super(tree, queue);
        mId = tree.mId;
        mName = tree.mName;
        mRoot = tree.mRoot;
    }
}
